name: novelt
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - ipykernel
  - pip:
      - annotated-types==0.6.0
      - anyio==4.3.0
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - decorator==4.4.2
      - distro==1.9.0
      - exceptiongroup==1.2.0
      - h11==0.14.0
      - httpcore==1.0.4
      - httpx==0.27.0
      - idna==3.6
      - imageio==2.34.0
      - imageio-ffmpeg==0.4.9
      - moviepy==1.0.3
      - numpy==1.24.4
      - openai==1.14.2
      - opencv-python==4.9.0.80
      - pillow==10.2.0
      - proglog==0.1.10
      - pydantic==2.6.4
      - pydantic-core==2.16.3
      - requests==2.31.0
      - sniffio==1.3.1
      - tqdm==4.66.2
      - urllib3==2.2.1